### ISSUE TITLE
License

### ISSUE THREAD

**Issue by haf** [juhovh/AaltoTLS#1]
Greetings,

Would it be possible to put a license, such as Apache 2.0 on this code-base?

Regards

**Comment by haf** [comment]
I read the code, and can see you've applied MIT to all of the code-base. =) Great.

**Comment by juhovh** [comment]
This is valid issue in a way, because the license is not explicitly mentioned in the README and there is no LICENSE file, could add it somewhere there.

Please notice that the code is written at the University with extensibility and readability in mind, the performance is quite awful and the SSL/TLS API is not quite finished yet, would need some work to get it into a usable state. But it should be able to perform quite wide range of handshakes quite ok and run on mono.

**Comment by haf** [comment]
I'm trying to get to a state of TLS bliss in [Logary](https://github.com/logary/logary) and [Suave](https://github.com/SuaveIO/suave) =). Considering this library versus https://github.com/haf/miTLS or https://github.com/marcominetti/openssl-net

**Comment by haf** [comment]
Do you think it would be possible to merge the abstractions and code into miTLS? I'm really after the client-parts where you can do hand-shakes. I have [updated the code](https://github.com/haf/miTLS) to the latest 0.8.1 version now.
